django_table_with_sort_and_export/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('studentapp.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('student_list',views.student_list,name='student_list'),
    path('student_list_using_datatables.net',views.student_list_using_datatables,name='student_list_using_datatables'),
    path('csv_download',views.csv_download,name='csv_download'),
    path('generate_students',views.generate_students,name='generate_students')
    
]

studentapp/models.py
from django.db import models

# Create your models here.


class Country(models.Model):
    name = models.CharField(max_length=50,unique=True)

    def __str__(self):
        return self.name

class State(models.Model):
    country = models.ForeignKey(Country,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name



class Grade(models.Model):
    name = models.CharField(max_length=50,unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


gender_options = (('','Choose Gender'),('M','Male'),('F','Female'))
section_options = (('','Choose Section'),('A','A'),('B','B'),('C','C'),('D','D'))


class Student(models.Model):    
    name = models.CharField(max_length=50)
    roll_no = models.CharField(max_length=50,unique=True)
    age = models.IntegerField()
    gender = models.CharField(choices=gender_options,max_length=1)
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    grade = models.ForeignKey(Grade,on_delete=models.CASCADE)
    section = models.CharField(choices=section_options,max_length=1)


    def __str__(self):
        return self.name



    class Meta:
        ordering = ['name']

studentapp/views.py
from django.shortcuts import render
from .models import Student, State, Grade
import csv
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def home(request):
    return render(request, 'home.html')


def student_list(request):   
    order = request.GET.get('order')
    field = request.GET.get('field')
    export = request.GET.get('export')
    page = request.GET.get('page',1)
    if field is None:
        field = "name"
    if order is None:
        order = "ASC"

    if order == "ASC":
        student_list = Student.objects.all().order_by(field)
    else:
        student_list = Student.objects.all().order_by('-'+str(field))

    if export == "yes":
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="student_list.csv"'

        writer = csv.writer(response)
        writer.writerow(['Name', 'Roll No', 'Gender', 'Age','Grade','Section','State','Country'])

        students = student_list.values_list('name', 'roll_no', 'gender', 'age','grade__name','section','state__name','state__country__name')
        for student in students:
            writer.writerow(student)
        return response

    paginator = Paginator(student_list, 20)

    try:
        students = paginator.page(page)
    except PageNotAnInteger:
        students = paginator.page(1)
    except EmptyPage:
        students = paginator.page(paginator.num_pages)

    context = {
        'students' : students,
        'order' : order,
        'field' : field,
    }
    return render(request, 'students_list.html', context)


def student_list_using_datatables(request):  
    students = Student.objects.all()
    context = {
        'students' : students,      
    }
    return render(request, 'students_list_datatables.html', context)

def csv_download(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="student_list.csv"'
    writer = csv.writer(response)
    writer.writerow(['Name', 'Roll No', 'Gender', 'Age','Grade','Section','State','Country'])
    students = Student.objects.all().values_list('name', 'roll_no', 'gender', 'age','grade__name','section','state__name','state__country__name')
    for student in students:
        writer.writerow(student)

    return response


def generate_students(request):
    state = State.objects.order_by('?').first()
    grade = Grade.objects.order_by('?').first()
    for i in range(1,10000):
        Student.objects.create(name="Student "+str(i),roll_no="24HG"+str(i),age=19,gender='M',state=state,grade=grade,section="A")
    return HttpResponse("Done")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Django Table Sort & Export</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  {% block header %}


  {% endblock %}

  <style>
    .border-none{
      border:none; 
      background-color: #ffffff;
    }
    .span-inline{
      display: inline-block;
      margin: 0;
    }
  </style>
</head>
<body>
    <!-- As a heading -->
    <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <span class="navbar-brand mb-0 h1 p-2"><a class="text-black" href="{% url 'home' %}">Django Table (Sort&Export)</a></span>
    </div>
    </nav>
    {% block content %}

    {% endblock %}

    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
          <div class="col-md-4 d-flex align-items-center">
            
            <span class="text-muted">Madhan Umk - Python/Django Developer</span>
          </div>
      
          <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="https://madhanumk.github.io/"><i class="bi bi-globe"></i></a></li>
            <li class="ms-3"><a class="text-muted" href="https://github.com/madhanumk"><i class="bi bi-github"></i></a></li>
            <li class="ms-3"><a class="text-muted" href="https://www.linkedin.com/in/madhanumk/"><i class="bi bi-linkedin"></i></a></li>
            <li class="ms-3"><a class="text-muted" href="https://twitter.com/Madhanumk"><i class="bi bi-twitter"></i></a></li>
          </ul>
        </footer>
      </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-sm-6 mt-2">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Table Sort & Export using datatables.net</h5>
            <p class="card-text">Used: datatables.net javascript library</p>
            <p>Note: If you have more than 3000 rows, avoid using datatables.net because the rendering process is too long (django template engine side).</p>
            <a href="{% url 'student_list_using_datatables' %}" class="btn btn-primary">View Demo</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 mt-2">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Table Sort & Export using Django  </h5>
            <p class="card-text"> Used: Dajngo pagination, python csv, order by query.</p>
            <a href="{% url 'student_list' %}" class="btn btn-primary">View Demo</a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/students_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load pagination_tags %}

{% block content %}   
  <div class="container mt-2">
    <div class="row">
      <div class="col-sm-2">    
          
        </div>

        <div class="col-sm-9">
          <div class="row">
            <div class="col-sm-6">
              <h4>Student List</h4>
            </div>
            <div class="col-sm-6">
              <form method="get" action="{% url 'student_list' %}" target="_blank">
                <input type="hidden" value="{{order}}" name="order"> <input type="hidden" value="{{field}}" name="order"> <input type="hidden" value="yes" name="export"> 
                <button type="submit"  class="btn btn-dark float-end">Export as CSV</button>
              </form>
              
            </div>
          </div>
          
          

          <table class="table table-striped table-bordered mt-2" id="example">
              <thead>
                <tr>
                  
                  <th><form method="get"><span class="span-inline">Name</span>  {% if field == "name" %} {% if order == "ASC" %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-up-alt float-end"></i></button>  {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-down float-end"></i>  </button> {% endif %} {% else %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-arrow-down-up "></i></button>  {% endif %}</form></th>
                  <th><form method="get"><span class="span-inline">Roll No</span>   {% if field == "roll_no" %} {% if order == "ASC" %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="roll_no" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-up-alt float-end"></i></button>  {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="roll_no" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-down float-end"></i>  </button> {% endif %} {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="roll_no" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-arrow-down-up "></i></button>  {% endif %}</form></th>
                  <th><form method="get"><span class="span-inline">Gender</span> {% if field == "gender" %} {% if order == "ASC" %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="gender" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-up-alt float-end"></i></button>  {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="gender" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-down float-end"></i>  </button> {% endif %} {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="gender" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-arrow-down-up "></i></button>  {% endif %}</form></th>
                  <th><form method="get"><span class="span-inline">Age </span> {% if field == "age" %} {% if order == "ASC" %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="age" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-up-alt float-end"></i></button>  {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="age" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-down float-end"></i>  </button> {% endif %} {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="age" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-arrow-down-up "></i></button>  {% endif %}</form></th>
                  <th><form method="get"><span class="span-inline">Grade</span> {% if field == "grade__name" %} {% if order == "ASC" %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="grade__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-up-alt float-end"></i></button>  {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="grade__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-down float-end"></i>  </button> {% endif %} {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="grade__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-arrow-down-up "></i></button>  {% endif %}</form></th>
                  <th><form method="get"><span class="span-inline">Section</span> {% if field == "section" %} {% if order == "ASC" %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="section" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-up-alt float-end"></i></button>  {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="section" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-down float-end"></i>  </button> {% endif %} {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="section" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-arrow-down-up "></i></button>  {% endif %}</form></th>
                  <th><form method="get"><span class="span-inline">State</span> {% if field == "state__name" %} {% if order == "ASC" %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="state__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-up-alt float-end"></i></button>  {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="state__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-down float-end"></i>  </button> {% endif %} {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="state__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-arrow-down-up "></i></button>  {% endif %}</form></th>
                  <th><form method="get"><span class="span-inline">Country </span>{% if field == "state__country__name" %} {% if order == "ASC" %} <input type="hidden" value="DESC" name="order"> <input type="hidden" value="state__country__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-up-alt float-end"></i></button>  {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="state__country__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-sort-down float-end"></i>  </button> {% endif %} {% else %} <input type="hidden" value="ASC" name="order"> <input type="hidden" value="state__country__name" name="field"> <button class="border-none float-end" type="submit"><i class="bi bi-arrow-down-up "></i></button>  {% endif %}</form></th>

                  </form>
                </tr>
              </thead>
              <tbody>
                  {% for student in students %}
                      <tr>
                          <td>{{student.name}}</td>
                          <td>{{student.roll_no}}</td>
                          <td>{{student.get_gender_display}}</td>
                          <td>{{student.age}}</td>
                          <td>{{student.grade}}</td>
                          <td>{{student.section}}</td>
                          <td>{{student.state}}</td>
                          <td>{{student.state.country}}</td>
                      </tr>
                  {% endfor %}
              </tbody>
            </table>
            <nav aria-label="Page navigation example">          
              {% if students.paginator.num_pages > 1 %}
                <ul class="pagination justify-content-center">
                    {% if students.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?{% param_replace page=1 %}">
                                First
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                First
                            </a>
                        </li>
                    {% endif %}
                    {% if students.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?{% param_replace page=students.previous_page_number %}">
                                &laquo;
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                &laquo;
                            </a>
                        </li>
                    {% endif %}
                    {% for i in students.paginator.page_range %}
                        {% if students.number == i %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ i }} <span class="sr-only"></span>
                                </a>
                            </li>
                        {% elif students.number > i|add:"-5" and students.number < i|add:"+5"%}
                            <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if students.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?{% param_replace page=students.next_page_number %}">
                                &raquo;
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                &raquo;
                            </a>
                        </li>
                    {% endif %}
                    {% if students.paginator.num_pages != students.number %}
                        <li class="page-item">
                            <a class="page-link" href="?{% param_replace page=students.paginator.num_pages %}">
                                Last
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                    {% endif %}
                </ul>
              {% endif %}
            </nav>

        </div>
      
    </div>
  </div>
{% endblock %}

templates/students_list_datatables.html
{% extends 'base.html' %}


{% block header %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.3.2/js/dataTables.buttons.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script scr="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.print.min.js"></script>
  <link href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/buttons/2.3.2/css/buttons.dataTables.min.css" rel="stylesheet">
  <style>

    .border-none{
      border:none; 
      background-color: #ffffff;
    }
    .span-inline{
      display: inline-block;
      margin: 0;
    }
  </style>

{% endblock %}

{% block content %}  
  <div class="container mt-2">
    <div class="row">
      <div class="col-sm-2">    
          
        </div>

        <div class="col-sm-9">
          <div class="row">
            <div class="col-sm-6">
              <h4>Student List Using Datatables.net</h4>
            </div>
            <div class="col-sm-6">
              
            </div>
          </div>
          
          

          <table class="" id="example">
              <thead>
                <tr>
                  
                  <th>Name  </th>
                  <th>Roll No   </th>
                  <th>Gender </form></th>
                  <th>Age  </th>
                  <th>Grade </th>
                  <th>Section </th>
                  <th>State </th>
                  <th>Country </th>

                  </form>
                </tr>
              </thead>
              <tbody>
                  {% for student in students %}
                      <tr>
                          <td>{{student.name}}</td>
                          <td>{{student.roll_no}}</td>
                          <td>{{student.get_gender_display}}</td>
                          <td>{{student.age}}</td>
                          <td>{{student.grade}}</td>
                          <td>{{student.section}}</td>
                          <td>{{student.state}}</td>
                          <td>{{student.state.country}}</td>
                      </tr>
                  {% endfor %}
              </tbody>
            </table>
        </div>
      
    </div>
  </div>

  <script>
      $(document).ready(function() {
          $('#example').DataTable( {
              dom: 'Bfrtip',
              buttons: [
                  'excel', 
              ]
          } );
      } );
  </script>

{% endblock %}